export const LOAD_REVIEWS = 'LOAD_REVIEWS';
export const LOAD_COMPLAINTS = 'LOAD_COMPLAINTS';

export const NOTIFICATION = 'NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';


export const COMMENT_REPLY = 'COMMENT_REPLY';
export const DELETE_COMMENT_REPLY = 'DELETE_COMMENT_REPLY';


export const SEARCH = 'SEARCH';